= Developer Community in Bangladesh
;
:revnumber: {version}
:revdate: {localdate}
:toc:
:toc-placement!:



List of developers to help tech companies to find the best resources.

(C) 2022 The original authors #Xihad Islam.

NOTE: Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.



toc::[]


## How to add a new Developer?

* Fork the repository.
* Add the Developer in district order.
* Create pull request.

{nbsp} +
{nbsp} +


## Developers from : Sylhet
|===
|Developer Name |Bio |Expertise |Contact Info |Web presence 

|MD ZIADUL ISLAM
|Software Engineer at YO TECH
|Android, Flutter
|Email: xihad.bd@gmail.com 
|https://xihadulislam.github.io/[Website]



|===


{nbsp} +
{nbsp} +

=== Contribute
Contributions are always welcome! Create a pull request.


=== Copyright & License
Licensed under the MIT License, see the link:LICENSE[LICENSE] file for details.
