= à¦¬à¦¾à¦‚à¦²à¦¾à¦¦à§‡à¦¶à§‡ à¦®à§‹à¦¬à¦¾à¦‡à¦² à¦…à§à¦¯à¦¾à¦ªà§à¦²à¦¿à¦•à§‡à¦¶à¦¨ à¦¡à§‡à¦­à§‡à¦²à¦ªà¦¾à¦° à¦•à¦®à¦¿à¦‰à¦¨à¦¿à¦Ÿà¦¿
;
:revnumber: {version}
:revdate: {localdate}
:toc:
:toc-placement!:

(C) 2022 The original author  https://github.com/xihadulislam/[@XihadIslam.]


Nowadays contribution in git has become the most important part of every developer's career.ðŸ¤© The more you contribute, most you have a chance to be eligible to get hired by tech companies. So we have come up with an idea to make a platform to list all mobile developers in Bangladesh according to their region. :heart:

Some renowned companies in Bangladesh are searching for skillful and intelligent brains. And some foreign companies are also opening branches in Bangladesh or they try to hire Mobile Application Developers from Bangladesh and for that they need worthy individuals.ðŸ¥‡ So This community can be a stage to find and get in touch with developers of skills.ðŸ’ª So list yourself here and increase your opportunity to be known by people worldwide.ðŸ†


== Find Mobile Developers region wise ðŸ”


toc::[]

{nbsp} +

NOTE:  Listing in this community is not that tough.ðŸ˜„ You can make yourself enlisted here very easily by following the below steps.ðŸ‘‡

{nbsp} +

== Division of Bangladesh

=== Sylhet-à¦¸à¦¿à¦²à§‡à¦Ÿ

|===
|Name |Bio |Expertise |Contact Info

// start from here
|Md Ziadul Islam
|Software Engineer at YO TECH

2021 - Present

|Android, Flutter, Java, Kotlin, MVVM, Coroutine, Live Data, Dagger Hilt, Push Notification, Unit Testing, REST API, Retrofit2, Database [ Firebase , Room, SQLite ], Git Version Control.
|xihad.bd@gmail.com

https://xihadulislam.github.io/[Portfolio], https://www.linkedin.com/in/xihadislam/[Linkedin], https://leetcode.com/xihadislam/[Leetcode], https://twitter.com/xihadulislam/[Twitter], https://www.youtube.com/channel/UCz5x81XnMGnW5KB5lYQsN9Q/[Youtube], https://www.facebook.com/xihadislam00/[Facebook]

// end of a table


// start from here
|PRABAL BHATTACHARJEE
|Software Engineer at YO TECH

2020 - Present
|Android, Flutter, JAVA, Kotlin, MVVM, Live Data, Push Notification, Unit Testing, REST API, Retrifot, Database [ MYSQL, Firebase, SQLITE ], PHP, GIT Version Control
|prabal23.dev@gmail.com

Phone: +8801720848705

https://github.com/Prabal23/[GITHUB]
// end of a table

// start from here
|Sudipto Sarker
|Flutter Mobile Application Developer at YO TECH
|Android, Flutter
|Email: sudiptosarker05@gmail.com

https://sudiptosk08.github.io/[Website]
// end of a table

// start from here
|MD SHAHIN MIAH
|Software Engineer at YO TECH
|Android, Flutter
|Email: shahintahsan225@gmail.com

What'sapp : +8801788885000

https://github.com/ShahinMohammad-insaneCoder[Github]
// end of a table

// start from here
|Farhana Akter Maha
|Software Engineer at YO TECH
|Android, Flutter, Java,Push Notification,REST API, Database [ Firebase, SQLite ], Git Version Control.
|mahafarhana@gmail.com

 https://github.com/mahafarhana/[Portfolio], https://www.linkedin.com/in/farhana-maha-0bb925164/[Linkedin], https://twitter.com/Farhanamaha/[Twitter]
// end of a table


// start from here
|S.m. Kamal Hussain Shahi
|Senior Software Engineer at TenTwenty Digital Agency, Dubai

2022 - Present

|Flutter, Flutter-Web, Flutter-Desktop, Android, Java, Kotlin, Swift (Basic), MVVM, MVC, SDUI, TDD, Push Notification, Unit Testing, Widget Testing, Firebase, REST API, Retrofit2, Database [ Room, SQLite ], PHP, Laravel, MySql, Git Version Control.
|kamal@tentwenty.me (Official), s.m.kamalhussain@gmail.com (Personal)

https://shahi5472.github.io/home[Portfolio], https://github.com/shahi5472[Github], https://www.linkedin.com/in/s-m-kamal-hussain-shahi-b121a8179[Linkedin]

// end of a table

// start from here
|Provakor Das Konik
|Remote Software Engineer

2022 - Present

|Android Fundamental, Java, OOP, 
LiveData, **MVVM, Clean Code,** 
Room, Firestore DB, DataBinding, ViewBinding, XML Layout Design,
Dependency Injection (Dagger, Hilt),
Firebase (Auth, Notification, Cloud, Analytics), 
Threads, Git and Github, Google Maps Api,
Memory leak detection, Sequence, Class, Case, ER Diagram, **Readable_code **


|Experience : Two Years
provakor.konik@gmail.com

Phone: +8801882563044

https://github.com/fakibuzzkonik/[GITHUB], https://www.linkedin.com/in/provakorkonik/[Linkedin]
// end of a table

// start from here
|Sajid Mohammad Ikram
|Flutter Developer


|Flutter, Git, Firebase, NodeJS - Express, MongoDb, OOP, C++.


|sajidmdikram@gmail.com

Phone: +8801877532330

https://github.com/Sajid-ikram/[Github], https://www.linkedin.com/in/sajid-ikram/[Linkedin]
// end of a table



|===

{nbsp} +
{nbsp} +

=== Dhaka-à¦¢à¦¾à¦•à¦¾

|===
|Name |Bio |Expertise |Contact Info

|MD Ziaur Rahman Shamim
|Flutter Developer
|Flutter, GetX, Provider, API, MVC, HTML, CSS, JS, Git, Firebase, MVC, error solving, clean coding.
|Email: zrshamim8822@gmail.com

Phone : +8801842357696

https://github.com/ZRShamim[Github], https://www.linkedin.com/in/ziaur-shamim/[Linkedin]

// end of a table

// start from here

|Md Shadat Rahman
|Junior Software Engineer at HelloTask
|Flutter, GraphQL, REST API, Database [ Firebase, Hive ], Git, C, Dart, Java, Kotlin, Swift, Python, FastAPI, Postgresql, Docker, Heroku, Postman, Insomnia, Jira, Trello, Manjaro Linux, vim.
|shadat.rahman.464@gmail.com

 https://github.com/mdshadatrahman[Github], https://www.linkedin.com/in/shadat-rahman-208036165/[Linkedin]

// end of a table


// start from here
|Sushmoy Roy
|Mobile Application Developer at Onnorokom Pathshala

2022 - Present
| Flutter - Animation, Riverpod, GetX, Api, Firebase, MVVM, Clean Architecture, SQLITE, Hive

NodeJS - Express, MongoDb, React, NextJS
|Email: sushmoyr@gmail.com

Phone: +8801854489406

https://github.com/sushmoyr[GITHUB]

https://linkedin.com/in/sushmoyr/[LINKEDIN]
// end of a table

// start from here

|Md. Akter Hossain
|Software Developer at Ridealike Inc.
|Flutter, Dart, REST API, Database [ Firebase, Hive ], Git, C, Kotlin, Postman, Provider, MVP, MVVM, Bloc Pattern, OOP, Insomnia, Jira, Manjaro Linux.
|akterh.ja@gmail.com

+8801844664252

 https://github.com/akterridealike[Github], https://www.linkedin.com/in/akter-hossain-7570aa129/[Linkedin]

// end of a table



|===

{nbsp} +
{nbsp} +


=== Chittagong-à¦šà¦Ÿà§à¦Ÿà¦—à§à¦°à¦¾à¦®

|===
|Name |Bio |Expertise |Contact Info

|Mr. Developer
|Software Engineer at GOOGLE
|Etc, Etc
|Email: example@gmail.com

Phone : +88017xxxxxxx

https://example.com/[Website]



|===

{nbsp} +
{nbsp} +


=== Rajshahi-à¦°à¦¾à¦œà¦¶à¦¾à¦¹à§€

|===
|Name |Bio |Expertise |Contact Info

|Mr. Developer
|Software Engineer at GOOGLE
|Etc, Etc
|Email: example@gmail.com

Phone : +88017xxxxxxx

https://example.com/[Website]


|===

{nbsp} +
{nbsp} +


=== Barisal-à¦¬à¦°à¦¿à¦¶à¦¾à¦²

|===
|Name |Bio |Expertise |Contact Info
// start from here
|Mahamudul Hasan
|Junior Mobile Application Developer at Miicon Solutions
|Flutter, Dart, C++, Java SE, Firebase
|Email: mahamudulhasan.cse@gmail.com

What's app : +8801727493053

https://github.com/SyedMahamudulHasan[Github]
https://www.linkedin.com/in/syed-mahamudul-hasan-8a3196194/[Linkedin]
// end of a table

|===

{nbsp} +
{nbsp} +


=== Mymensingh-à¦®à¦¯à¦¼à¦®à¦¨à¦¸à¦¿à¦‚à¦¹

|===
|Name |Bio |Expertise |Contact Info

|Mr. Developer
|Software Engineer at GOOGLE
|Etc, Etc
|Email: example@gmail.com

Phone : +88017xxxxxxx

https://example.com/[Website]


|===

{nbsp} +
{nbsp} +



=== Rangpur-à¦°à¦‚à¦ªà§à¦°

|===
|Name |Bio |Expertise |Contact Info

|Mr. Developer
|Software Engineer at GOOGLE
|Etc, Etc
|Email: example@gmail.com

Phone : +88017xxxxxxx

https://example.com/[Website]


|===

{nbsp} +
{nbsp} +


=== Khulna-à¦–à§à¦²à¦¨à¦¾

|===
|Name |Bio |Expertise |Contact Info

|Mr. Developer
|Software Engineer at GOOGLE
|Etc, Etc
|Email: example@gmail.com

Phone : +88017xxxxxxx

https://example.com/[Website]


|===

{nbsp} +
{nbsp} +


== How to add a new Developer?

* Fork the repository.
* Add the Developer in division order.
* Create pull request.

{nbsp} +


## Found this project useful â­
* Support by clicking the :star: button on the upper right of this page. :v:

{nbsp} +

NOTE: Updating it on daily basis as much as possible, work in progess[WIP].


{nbsp} +


## Thanks to all contributors â¤
image:https://contrib.rocks/image?repo=xihadulislam/Mobile-Dev-Community-in-Bangladesh[link="https://github.com/xihadulislam/Mobile-Dev-Community-in-Bangladesh/graphs/contributors"]

{nbsp} +


== Contributions & Licensed

=== -> Contribute

 Contributions are always welcome!Create a pull request.
 

=== -> Copyright & License

Licensed under the MIT License, see the link:LICENSE[LICENSE] file for details.
